version: "3.8"

services:
  api: 
    build: .
    container_name: "pos-plugin-api"
    ports:
      - "8080:8080"
    restart: always
    networks:
      - fullstack

networks:
  fullstack:
    driver: bridge